version: '3'
services:

  mongodb:
    image: mongo
    container_name: mongodb
    command: mongod
    ports:
      - "27017:27017"
    volumes:
      - ../data:/data/db

  three-tier-golang:
    build: .
    container_name: go-tuts
    image: three-tier-golang
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: 'mongodb'
      DATABASE_NAME: 'go-tuts'
      PORT: '8080'
    links:
      - mongodb
